# Creating the model to predict the excessive absence to work with the help of Machine Learning

## And we already have the preprocessed dataset with us, which we did in the previous notebook 

## Author : Byri Manoj S

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_Preprocessed.csv')
data_preprocessed.head()

Reasons_1  Reasons_2  Reasons_3  Reasons_4  Month Value  Day of the week  \
0          0          0          0          1            7                1   
1          0          0          0          0            7                1   
2          0          0          0          1            7                2   
3          1          0          0          0            7                3   
4          0          0          0          1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## Preprocessing the Absenteeism Time in Hours

### We will take the median of the column and divide it into two classes, one is moderate absence & Excessive Absence as 0 & 1

In [3]:
Median = data_preprocessed['Absenteeism Time in Hours'].median()
Median

3.0

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > Median, 1, 0)

In [5]:
data_preprocessed['Targets'] = targets

In [6]:
data_preprocessed.head(10)

Reasons_1  Reasons_2  Reasons_3  Reasons_4  Month Value  Day of the week  \
0          0          0          0          1            7                1   
1          0          0          0          0            7                1   
2          0          0          0          1            7                2   
3          1          0          0          0            7                3   
4          0          0          0          1            7                3   
5          0          0          0          1            7                4   
6          0          0          0          1            7                4   
7          0          0          0          1            7                4   
8          0          0          1          0            7                0   
9          0          0          0          1            7                0   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   
5                     179                51   38                  239.554   
6                     361                52   28                  239.554   
7                     260                50   36                  239.554   
8                     155                12   34                  239.554   
9                     235                11   37                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   
5               31          0         0     0                          2   
6               27          0         1     4                          8   
7               23          0         4     0                          4   
8               25          0         2     0                         40   
9               29          1         1     1                          8   

   Targets  
0        1  
1        0  
2        0  
3        1  
4        0  
5        0  
6        1  
7        1  
8        1  
9        1

In [7]:
data_preprocessed = data_preprocessed.drop(['Absenteeism Time in Hours'], axis=1)

In [8]:
data_targets = data_preprocessed.copy()

In [9]:
data_targets.head()

Reasons_1  Reasons_2  Reasons_3  Reasons_4  Month Value  Day of the week  \
0          0          0          0          1            7                1   
1          0          0          0          0            7                1   
2          0          0          0          1            7                2   
3          1          0          0          0            7                3   
4          0          0          0          1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Targets  
0               30          0         2     1        1  
1               31          0         1     0        0  
2               31          0         0     0        0  
3               24          0         2     0        1  
4               30          0         2     1        0

In [10]:
#inputs
unscaled_inputs = data_targets.iloc[:,:-1]
targetss = data_targets['Targets']
unscaled_inputs

Reasons_1  Reasons_2  Reasons_3  Reasons_4  Month Value  Day of the week  \
0            0          0          0          1            7                1   
1            0          0          0          0            7                1   
2            0          0          0          1            7                2   
3            1          0          0          0            7                3   
4            0          0          0          1            7                3   
..         ...        ...        ...        ...          ...              ...   
695          1          0          0          0            5                2   
696          1          0          0          0            5                2   
697          1          0          0          0            5                3   
698          0          0          0          1            5                3   
699          0          0          0          1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [12]:
scaler.fit(unscaled_inputs)

StandardScaler()

In [13]:
scaled_inputs = scaler.transform(unscaled_inputs)

In [14]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [15]:
from sklearn.model_selection import train_test_split as tts

In [16]:
x_train, x_test, y_train, y_test = tts(scaled_inputs, targetss, random_state=360, train_size=0.8)

# Modeling

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import *

In [18]:
model = LogisticRegression(verbose=2)

In [19]:
model.fit(x_train,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


LogisticRegression(verbose=2)

In [20]:
model.score(x_train,y_train)

0.7821428571428571

In [21]:
prediction = model.predict(x_train)

In [22]:
prediction == y_train

684     True
570     True
377     True
580     True
654     True
       ...  
290    False
520     True
578     True
572     True
64      True
Name: Targets, Length: 560, dtype: bool

In [23]:
np.sum(prediction == y_train)

438

In [24]:
# Therefore accuracy can be obtained by divided by total number of True by no of obs
np.sum(prediction == y_train) / prediction.shape

array([0.78214286])

In [25]:
model.coef_

array([[ 2.18725264,  0.3194068 ,  1.50223268,  1.39421418,  0.11467178,
        -0.17774825,  0.77300768, -0.11449763, -0.21175414, -0.03830063,
         0.38053395, -0.04710114,  0.41144407, -0.31551831]])

In [26]:
model.intercept_

array([-0.3076174])

In [27]:
summary = pd.DataFrame(data=unscaled_inputs.columns.values, columns=['Feature Names'])
summary['Weights'] = np.transpose(model.coef_)
summary

Feature Names   Weights
0                 Reasons_1  2.187253
1                 Reasons_2  0.319407
2                 Reasons_3  1.502233
3                 Reasons_4  1.394214
4               Month Value  0.114672
5           Day of the week -0.177748
6    Transportation Expense  0.773008
7          Distance to Work -0.114498
8                       Age -0.211754
9   Daily Work Load Average -0.038301
10          Body Mass Index  0.380534
11                Education -0.047101
12                 Children  0.411444
13                     Pets -0.315518

In [28]:
summary.index = summary.index + 1
summary.loc[0] = ['Bias', model.intercept_[0]]
summary = summary.sort_index()
summary

Feature Names   Weights
0                      Bias -0.307617
1                 Reasons_1  2.187253
2                 Reasons_2  0.319407
3                 Reasons_3  1.502233
4                 Reasons_4  1.394214
5               Month Value  0.114672
6           Day of the week -0.177748
7    Transportation Expense  0.773008
8          Distance to Work -0.114498
9                       Age -0.211754
10  Daily Work Load Average -0.038301
11          Body Mass Index  0.380534
12                Education -0.047101
13                 Children  0.411444
14                     Pets -0.315518

In [29]:
summary['Odds_Ratio'] = np.exp(summary.Weights)
summary

Feature Names   Weights  Odds_Ratio
0                      Bias -0.307617    0.735197
1                 Reasons_1  2.187253    8.910699
2                 Reasons_2  0.319407    1.376311
3                 Reasons_3  1.502233    4.491706
4                 Reasons_4  1.394214    4.031805
5               Month Value  0.114672    1.121505
6           Day of the week -0.177748    0.837153
7    Transportation Expense  0.773008    2.166272
8          Distance to Work -0.114498    0.891814
9                       Age -0.211754    0.809164
10  Daily Work Load Average -0.038301    0.962424
11          Body Mass Index  0.380534    1.463066
12                Education -0.047101    0.953991
13                 Children  0.411444    1.508995
14                     Pets -0.315518    0.729411

In [30]:
summary.sort_values('Odds_Ratio', ascending=False)

Feature Names   Weights  Odds_Ratio
1                 Reasons_1  2.187253    8.910699
3                 Reasons_3  1.502233    4.491706
4                 Reasons_4  1.394214    4.031805
7    Transportation Expense  0.773008    2.166272
13                 Children  0.411444    1.508995
11          Body Mass Index  0.380534    1.463066
2                 Reasons_2  0.319407    1.376311
5               Month Value  0.114672    1.121505
10  Daily Work Load Average -0.038301    0.962424
12                Education -0.047101    0.953991
8          Distance to Work -0.114498    0.891814
6           Day of the week -0.177748    0.837153
9                       Age -0.211754    0.809164
0                      Bias -0.307617    0.735197
14                     Pets -0.315518    0.729411

### With the help of odds ratio & weights we can clearly see that Daily work load avg, Day of the week, Education, Distance to work are useless

# Testing the Model

In [31]:
model.score(x_test,y_test)

0.7214285714285714

In [32]:
prediction_proba = model.predict_proba(x_test)

In [33]:
prediction_proba[:,1] # Probaility of becoming 1 (excessive Absent)

array([0.53596047, 0.45248   , 0.3512811 , 0.92425617, 0.58638761,
       0.55525932, 0.50582359, 0.28582457, 0.20543238, 0.07463102,
       0.17337567, 0.73108161, 0.45005203, 0.23300033, 0.18039221,
       0.38890915, 0.25849484, 0.60305845, 0.07789988, 0.12913316,
       0.13632112, 0.27972825, 0.81236463, 0.91958134, 0.2001718 ,
       0.65810981, 0.27320694, 0.2024084 , 0.59301076, 0.21378794,
       0.04205232, 0.2948247 , 0.25445156, 0.37164497, 0.1333466 ,
       0.2517938 , 0.96687272, 0.95166382, 0.20671117, 0.53949373,
       0.40779098, 0.15496957, 0.90049298, 0.16444379, 0.15541789,
       0.91220724, 0.53145353, 0.52309223, 0.91033238, 0.08336488,
       0.6016156 , 0.28150497, 0.17185026, 0.90138175, 0.73509961,
       0.76708381, 0.18492921, 0.16077032, 0.17644353, 0.42867392,
       0.13115726, 0.18358507, 0.17424259, 0.42188944, 0.23122131,
       0.12552144, 0.00717845, 0.89871535, 0.74174251, 0.67817046,
       0.9827708 , 0.92630039, 0.09912124, 0.07720828, 0.22133

In [34]:
df_test = pd.DataFrame(data=prediction_proba[:,1], columns=['Prediction Probalility of 1'])

In [35]:
df_test

Prediction Probalility of 1
0                       0.535960
1                       0.452480
2                       0.351281
3                       0.924256
4                       0.586388
..                           ...
135                     0.491492
136                     0.132682
137                     0.505679
138                     0.102517
139                     0.376443

[140 rows x 1 columns]